library(ggplot2)
library("faraway")
require(faraway)
library("leaps")
require(MASS)
library("data.table", lib.loc="~/R/win-library/3.5")
library("MLmetrics", lib.loc="~/R/win-library/3.5")
library(reshape2)

binUnif= function(n,a,b,intv,mfactor)
{
  message = paste("From",a)
  message = paste(message,"to")
  message = paste(message,b)
  print(message)
  resultsog = runif(n,a,b)
  results = floor(resultsog*mfactor)
  data = data.frame(results)
  vals = seq(a,b,intv)
  pdf(paste(b-1,"graph.pdf",sep="")) 
  p<-ggplot(data=data, aes(x=factor(data[,1]))) +geom_bar(stat="count") + scale_x_discrete(labels=vals)
  print(p)
  dev.off()
  #barplot(results,main="whatev",width=0.5)
  print(median(resultsog))
  getmode = table(resultsog)
  print(which.max(getmode))
  #print(forMode[c(1:10),])
}
expoMedMode = function(n,rate)
{
  resultsog = rexp(n,rate=rate)
  results = floor(resultsog*10)
  data = data.frame(results)
  data = data.frame(data[data[,1]<25,])
  vals = seq(0,2.5,.1)
  p<-ggplot(data=data, aes(x=factor(data[,1]))) +geom_bar(stat="count") + scale_x_discrete(labels=vals)
  print(p)
  #barplot(results,main="whatev",width=0.5)
  print(median(resultsog))
  getmode = table(resultsog)
  print(which.max(getmode))
}

